import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'zh';
const copy = {
  en: { today: 'Today', last7: 'Last 7 days', last30: 'Last 30 days', sessions: 'Sessions', projects: 'projects', tokens: 'Tokens', llmCalls: 'LLM calls', cost: 'Cost', tools: 'tools', avg: 'Avg duration', activeDays: 'active days', inbox: 'Sessions Inbox', activeBetween: 'Active between', reset: 'Reset dates', search: 'Search session, project, or prompt…', clear: 'Clear', showing: 'Showing', of: 'of', matching: 'matching sessions', loading: 'Loading…', loadMore: 'Load more', dateRange: 'Date range', active: 'Inbox filters active', connection: 'Connection error', retry: 'Retry', toggle: '中文', sessionDuration: 'Session duration', promptGroups: 'Prompt groups', toolCalls: 'Tool calls', totalCost: 'Total cost', sessionInfo: 'Session info', platform: 'Platform', startTime: 'Start time', modified: 'Modified', lastActivity: 'Last activity', created: 'Created', projectPath: 'Project path', sessionFile: 'Session file', openProject: 'Open project', openFolder: 'Open folder', overview: 'Overview', taskStatus: 'Task status', raw: 'Raw', noLlm: 'No LLM calls', noMessages: 'No visible messages', loadEarlier: 'Load earlier conversation', loadingShort: 'Loading…', user: 'User', thinking: 'Thinking', tool: 'Tool', text: 'Text', empty: 'Empty response', copy: 'Copy', copied: 'Copied', expand: 'Expand', collapse: 'Collapse', output: 'Output', error: 'Error', success: 'Success', noOutput: 'No output', incomplete: 'Incomplete', taskNotice: 'Task notification', bashOutput: 'Bash output', bashError: 'Bash error', records: 'records', assistantTurns: 'assistant turns', commands: 'commands', userPrompt: 'User prompt', subagentInput: 'User input', completed: 'Completed', failed: 'Failed', running: 'Running', cancelled: 'Cancelled', noSubagents: 'No visible subagent logs', logFile: 'Log file', metadata: 'Subagent metadata', noTaskSummary: 'No task status summary', taskStatusLabel: 'Task status', createdLabel: 'Created', updated: 'Updated', listed: 'Listed', fetched: 'Fetched', rawSession: 'Raw session records' },
  zh: { today: '今天', last7: '近7天', last30: '近30天', sessions: '会话', projects: '项目', tokens: 'Token', llmCalls: 'LLM 调用', cost: '成本', tools: '工具', avg: '平均时长', activeDays: '活跃天数', inbox: '会话收件箱', activeBetween: '活跃时间', reset: '重置日期', search: '搜索会话、项目或提示词…', clear: '清除', showing: '显示', of: '/', matching: '个匹配会话', loading: '加载中…', loadMore: '加载更多', dateRange: '日期范围', active: '收件箱筛选已启用', connection: '连接错误', retry: '重试', toggle: 'English', sessionDuration: '会话时长', promptGroups: '提示词分组', toolCalls: '工具调用', totalCost: '总成本', sessionInfo: 'Session 信息', platform: '平台', startTime: '开始时间', modified: '修改时间', lastActivity: '最后活动', created: '创建时间', projectPath: '项目路径', sessionFile: 'Session 文件', openProject: 'Open project', openFolder: 'Open folder', overview: '概览', taskStatus: '任务状态', raw: '原始', noLlm: '无 LLM 调用记录', noMessages: '当前筛选条件下无可见消息', loadEarlier: '加载更早对话', loadingShort: '加载中…', user: '用户', thinking: '思考', tool: '工具', text: '文本', empty: '空响应', copy: '复制', copied: '已复制', expand: '展开', collapse: '收起', output: '输出', error: '错误', success: '成功', noOutput: '无输出', incomplete: '不完整', taskNotice: '任务通知', bashOutput: 'Bash 输出', bashError: 'Bash 错误', records: '条记录', assistantTurns: '个 assistant turn', commands: '个 command', userPrompt: '用户提示词', subagentInput: '用户输入', completed: '已完成', failed: '失败', running: '运行中', cancelled: '已取消', noSubagents: '当前筛选条件下无可见 Subagent 日志', logFile: 'Log 文件', metadata: 'Subagent 元数据', noTaskSummary: '无任务状态摘要', taskStatusLabel: '任务状态', createdLabel: '创建', updated: '更新', listed: '列表', fetched: '获取', rawSession: '原始 Session 记录' },
} as const;
type Key = keyof typeof copy.en;
const Context = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: Key) => string } | null>(null);
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem('agentlens-language') as Language) || 'en');
  useEffect(() => {
    document.documentElement.lang = language === 'en' ? 'en-US' : 'zh-CN';
  }, [language]);
  const setLanguage = (value: Language) => { localStorage.setItem('agentlens-language', value); setLanguageState(value); };
  const value = useMemo(() => ({ language, setLanguage, t: (key: Key) => copy[language][key] }), [language]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() { const value = useContext(Context); if (!value) throw new Error('LanguageProvider is missing'); return value; }
